### ISSUE TITLE
Fix flakey smoke tests

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#187]
They currently need `runBlocking(Dispatchers.Default)` to prevent failing randomly, mainly due to concurrent modification exceptions mainly in `Interfaces#closeChildren`.

Find a better way of handling `tick()` and coroutine contexts for these tests.

**Comment by GregHib** [comment]
`PlayerMovementTaskTest`'s `Run odd step walks` `Run step` & `Walk step` all are frequently flakey too

**Comment by GregHib** [comment]
`TradeTest#Trade coins from one player to another()`
```
Exception in thread "Game loop @coroutine#11082" java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
	at world.gregs.voidps.engine.client.ui.Interfaces.closeChildrenOf(Interfaces.kt:99)
	at world.gregs.voidps.engine.client.ui.Interfaces.close(Interfaces.kt:41)
	at world.gregs.voidps.world.community.trade.TradeRequest.sendMain(TradeRequest.kts:117)
	at world.gregs.voidps.world.community.trade.TradeRequest$startTrade$1.invokeSuspend(TradeRequest.kts:70)
	at world.gregs.voidps.world.community.trade.TradeRequest$startTrade$1.invoke(TradeRequest.kts)
	at world.gregs.voidps.world.community.trade.TradeRequest$startTrade$1.invoke(TradeRequest.kts)
	at world.gregs.voidps.engine.action.Action$run$1.invokeSuspend(Action.kt:94)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
