### ISSUE TITLE
Concurrent read/write network exception

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#373]
Rarely when a player does something it'll cause a concurrent read+write exception inside `Client.send`. Caused by not writing on the same thread as reading. Although both are technically using the `Dispatchers.IO` context that doesn't guarantee the threads are the same. 

```
java.lang.IllegalStateException: ByteChannel[state: Reading+Writing] Concurrent writing is not supported
	at io.ktor.utils.io.internal.ReadWriteBufferState.startWriting$ktor_io(ReadWriteBufferState.kt:23)
	at io.ktor.utils.io.ByteBufferChannel.setupStateForWrite$ktor_io(ByteBufferChannel.kt:247)
	at io.ktor.utils.io.ByteBufferChannel.writeByte$suspendImpl(ByteBufferChannel.kt:2647)
	at io.ktor.utils.io.ByteBufferChannel.writeByte(ByteBufferChannel.kt)
	at io.ktor.utils.io.ByteWriteChannelKt.writeByte(ByteWriteChannel.kt:151)
	at world.gregs.voidps.network.Client.header(Client.kt:86)
	at world.gregs.voidps.network.Client.access$header(Client.kt:10)
	at world.gregs.voidps.network.Client$send$1.invokeSuspend(Client.kt:71)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**Comment by GregHib** [comment]
Wilderness levers caused this very frequently
